const express = require('express');
const router = express.Router();
const PermissionController = require('../controllers/PermissionController');
const authMiddleware = require('../middlewares/authMiddleware');
const {asyncHandle} = require('../utils/asyncHandle');
const checkPermission = require('../middlewares/checkPermission');
router.get('/', authMiddleware ,asyncHandle(PermissionController.getAllPermission));
router.post('/create', authMiddleware, checkPermission("create_permission") , asyncHandle(PermissionController.createPermission));
router.put('/update/:id', authMiddleware, checkPermission("update_permission") , asyncHandle(PermissionController.updatePermission));
router.delete('/:id', authMiddleware, checkPermission("delete_permission") , asyncHandle(PermissionController.deletePermission));
module.exports = router;